version: '3.11.4'
services:
  python:
    command: python3 main.py
    image: rakshya23/medical_insurance:g6
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80